import type { ProfissionalCompleto } from './profissionalTypes'

const enderecoBelem = {
  cep: '66010-971',
  logradouro: 'Av. Presidente Vargas',
  numero: '862',
  complemento: '',
  bairro: 'Campina',
  cidade: 'Belém',
  uf: 'PA',
} satisfies ProfissionalCompleto['detalhes']['endereco']

export const MOCK_PROFISSIONAIS_COMPLETO: ProfissionalCompleto[] = [
  {
    id: '1',
    nome: 'Dra. Ana Paula Ferreira',
    profissao: 'Médico(a)',
    registroProfissional: '14387/PA',
    localNome: 'HOSPITAL AMAZÔNIA',
    setores: ['ENFERMARIA'],
    detalhes: {
      fotoUrl: null,
      siglaConselho: 'CRM',
      email: 'ana.paula.ferreira@hospitalamazonia.org.br',
      cpf: '529.381.640-02',
      telefone: '(91) 3201-4500 ramal 2201',
      celular: '(91) 98765-1102',
      rg: '2.894.771-SSP/PA',
      orgaoEmissor: 'SSP/PA',
      dataNascimento: '18/06/1979',
      sexo: 'Feminino',
      nomeMae: 'Maria Lucia Ferreira',
      especialidade: 'Cardiologia',
      endereco: enderecoBelem,
      grupos: [
        { id: 'g1', nome: 'Equipe cardiologia dia', local: 'HOSPITAL AMAZÔNIA' },
        { id: 'g2', nome: 'Plantão avançado CC', local: 'HOSPITAL AMAZÔNIA' },
      ],
      dadosBancarios: {
        banco: '341 — Itaú Unibanco',
        agencia: '4521',
        conta: '13007-8',
        tipoConta: 'Corrente',
        pix: '52938164002',
      },
      resumoFaturamento:
        'Últimos 12 meses: 184 plantões registrados · notas fiscais em dia até competência atual · repasse médio líquido R$ 4.920,00/mês.',
      contratacao: {
        regime: 'Cooperado / credenciado SESPA',
        dataAdmissao: '03/03/2015',
        cargaHorariaSemanal: '36h semanais (12h x plantão)',
        numeroContrato: 'HC-HA-2015/00842',
      },
      afastamentos: [
        {
          inicio: '10/07/2023',
          fim: '24/07/2023',
          motivo: 'Licença médica prevista NT 14/2020',
        },
      ],
      habilidades: [
        'Ecocardiograma transtorácico',
        'ACM em urgência cardiológica',
        'Órtese post-revascularização',
      ],
      anexos: [
        {
          nome: 'CRM_-_Ana_PA.pdf',
          tipo: 'PDF',
          enviadoEm: '12/03/2024',
        },
        {
          nome: 'Titulo_especialidade.pdf',
          tipo: 'PDF',
          enviadoEm: '12/03/2024',
        },
      ],
    },
  },
  {
    id: '2',
    nome: 'Dr. Ricardo Mendes Oliveira',
    profissao: 'Médico(a)',
    registroProfissional: '98214/RJ',
    localNome: 'HOSPITAL AMAZÔNIA',
    setores: ['UTI-ADULTO'],
    detalhes: {
      fotoUrl: null,
      siglaConselho: 'CRM',
      email: 'ricardo.m.oliveira@email.com.br',
      cpf: '847.192.350-88',
      telefone: '(21) 2566-8890',
      celular: '(91) 99234-7788',
      rg: '9.887.661-DG/RJ',
      orgaoEmissor: 'DETRAN/RJ',
      dataNascimento: '02/01/1982',
      sexo: 'Masculino',
      nomeMae: 'Rosária Oliveira',
      especialidade: 'Medicina intensiva adulto',
      endereco: {
        cep: '66033-685',
        logradouro: 'Tv. Mauriti',
        numero: '312',
        complemento: '',
        bairro: 'Pedreira',
        cidade: 'Belém',
        uf: 'PA',
      },
      grupos: [{ id: 'g1', nome: 'UTI adulto cobertura 24h', local: 'HOSPITAL AMAZÔNIA' }],
      dadosBancarios: {
        banco: '237 — Bradesco',
        agencia: '1890',
        conta: '89012-4',
        tipoConta: 'Corrente',
        pix: '',
      },
      resumoFaturamento:
        'Competências 2025 em aberto: janeiro a março conferidos.',
      contratacao: {
        regime: 'RPA autônomo',
        dataAdmissao: '18/09/2020',
        cargaHorariaSemanal: '48h (escala definida mensal)',
        numeroContrato: 'HC-HA-2020/03112',
      },
      afastamentos: [],
      habilidades: ['Ventilação mecânica', 'PICC', 'Hemodinâmica básica'],
      anexos: [{ nome: 'contrato_escaneado.pdf', tipo: 'PDF', enviadoEm: '19/09/2020' }],
    },
  },
  {
    id: '3',
    nome: 'Enf.ª Mariana Costa Silva',
    profissao: 'Enfermeiro(a)',
    registroProfissional: '456789/MG',
    localNome: 'PRONTO SOCORRO CENTRAL',
    setores: ['Pediatria - Sala Vermelha', 'CENTRO DE TRIAGEM'],
    detalhes: {
      fotoUrl: null,
      siglaConselho: 'COREN',
      email: 'mariana.costasilva@saude.pa.gov.br',
      cpf: '391.028.470-15',
      telefone: '(91) 3202-8899',
      celular: '(91) 98112-9033',
      rg: 'MG-44.928.771',
      orgaoEmissor: 'SSP/MG',
      dataNascimento: '05/09/1988',
      sexo: 'Feminino',
      nomeMae: 'Ivone Costa Silva',
      especialidade: 'Emergência e trauma pediátrico',
      endereco: {
        cep: '66115-065',
        logradouro: 'Rod. Arthur Bernardes',
        numero: 'S/N',
        complemento: 'Anexo Ala B',
        bairro: 'Parque Verde',
        cidade: 'Belém',
        uf: 'PA',
      },
      grupos: [
        {
          id: 'g1',
          nome: 'Triagem rápida classificação Manchester',
          local: 'PRONTO SOCORRO CENTRAL',
        },
      ],
      dadosBancarios: {
        banco: '001 — Banco do Brasil',
        agencia: '3844-8',
        conta: '98234-X',
        tipoConta: 'Salário vínculo',
        pix: '39102847015',
      },
      resumoFaturamento: 'Bolsa cooperação + plantões extraordinários.',
      contratacao: {
        regime: 'CELETISTA vínculo indeterminado',
        dataAdmissao: '11/01/2019',
        cargaHorariaSemanal: '30h semanais',
        numeroContrato: 'PSC-2019/00412',
      },
      afastamentos: [],
      habilidades: ['PALS', 'Sala Vermelha', 'Curativo avançado'],
      anexos: [],
    },
  },
  {
    id: '4',
    nome: 'Dr. Felipe Augusto Nunes',
    profissao: 'Médico(a)',
    registroProfissional: '210398/MG',
    localNome: 'HOSPITAL REGIONAL NORTE',
    setores: ['ORTOPEDIA'],
    detalhes: {
      fotoUrl: null,
      siglaConselho: 'CRM',
      email: 'felipe.nunes.ortopedia@gmail.com',
      cpf: '612.934.820-41',
      telefone: '(91) 3288-7711',
      celular: '(91) 99340-5511',
      rg: 'MG-88.991.023',
      orgaoEmissor: 'SSP/MG',
      dataNascimento: '22/03/1976',
      sexo: 'Masculino',
      nomeMae: 'Helena Nunes Bezerra',
      especialidade: 'Ortopedia e traumatologia',
      endereco: {
        cep: '66095-682',
        logradouro: 'Tv. Tiradentes',
        numero: '55',
        complemento: '',
        bairro: 'Marco',
        cidade: 'Belém',
        uf: 'PA',
      },
      grupos: [{ id: 'g1', nome: 'Bloc cirúrgico ambulatorial', local: 'HRN' }],
      dadosBancarios: {
        banco: '104 — Caixa Econômica',
        agencia: '3891',
        conta: '8933-4',
        tipoConta: 'Corrente',
        pix: '61293482041',
      },
      resumoFaturamento: 'Honorários procedimentos CCIH + plantões sala vermelha.',
      contratacao: {
        regime: 'Credenciamento tercerizado',
        dataAdmissao: '06/06/2017',
        cargaHorariaSemanal: '24h médias',
        numeroContrato: 'HRN-2017/00201',
      },
      afastamentos: [],
      habilidades: ['Artroscopia joelho', 'Fixação externa urgência'],
      anexos: [{ nome: 'diploma_ortopedia.pdf', tipo: 'PDF', enviadoEm: '01/06/2017' }],
    },
  },
  {
    id: '5',
    nome: 'Dr. Carlos Eduardo Martins',
    profissao: 'Médico(a)',
    registroProfissional: '77102/SP',
    localNome: 'HOSPITAL AMAZÔNIA',
    setores: ['CARDIOLOGIA', 'PRONTO ATENDIMENTO'],
    detalhes: {
      fotoUrl: null,
      siglaConselho: 'CRM',
      email: 'c.martins.pa@yahoo.com.br',
      cpf: '221.938.740-71',
      telefone: '(91) 3201-2200',
      celular: '(91) 99101-8844',
      rg: '32.887.991-3',
      orgaoEmissor: 'SSP/SP',
      dataNascimento: '14/11/1985',
      sexo: 'Masculino',
      nomeMae: 'Eduarda Martins',
      especialidade: 'Cardiologia clínica',
      endereco: { ...enderecoBelem },
      grupos: [
        {
          id: 'g1',
          nome: 'PA cardiológico manhã',
          local: 'HOSPITAL AMAZÔNIA',
        },
      ],
      dadosBancarios: {
        banco: '341 — Itaú',
        agencia: '8891',
        conta: '22190-7',
        tipoConta: 'Corrente',
        pix: '',
      },
      resumoFaturamento: 'Início vínculo 2022 — sem pendências.',
      contratacao: {
        regime: 'RPA cooperado',
        dataAdmissao: '07/07/2022',
        cargaHorariaSemanal: '36h semanais',
        numeroContrato: 'HC-HA-2022/01993',
      },
      afastamentos: [],
      habilidades: ['ECG de alto volume', 'Bloqueios AV'],
      anexos: [],
    },
  },
  {
    id: '6',
    nome: 'Enf. Ricardo Souza Lima',
    profissao: 'Enfermeiro(a)',
    registroProfissional: '331122/PA',
    localNome: 'HOSPITAL REGIONAL NORTE',
    setores: ['UTI-ADULTO'],
    detalhes: {
      fotoUrl: null,
      siglaConselho: 'COREN',
      email: 'ricardo.sl@outlook.com',
      cpf: '903.771.940-92',
      telefone: '(91) 3288-6610',
      celular: '(91) 98222-6610',
      rg: '3.892.221-SSP/PA',
      orgaoEmissor: 'SSP/PA',
      dataNascimento: '30/04/1987',
      sexo: 'Masculino',
      nomeMae: 'Célia Souza',
      especialidade: 'UTI neonatal não — adulto apenas',
      endereco: {
        cep: '66087-661',
        logradouro: 'Tv. Benjamin Constant',
        numero: '1202',
        complemento: '',
        bairro: 'Pedreira',
        cidade: 'Belém',
        uf: 'PA',
      },
      grupos: [{ id: 'g1', nome: 'Enfermagem central UTI HRN', local: 'HRN' }],
      dadosBancarios: {
        banco: '237 — Bradesco',
        agencia: '2201',
        conta: '33445-9',
        tipoConta: 'Corrente',
        pix: '90377194092',
      },
      resumoFaturamento: 'Repasse mensal consolidado SESPA.',
      contratacao: {
        regime: 'Intermitente lei 13.467',
        dataAdmissao: '04/08/2021',
        cargaHorariaSemanal: 'Variável até 40h/mês',
        numeroContrato: 'HRN-2021/00778',
      },
      afastamentos: [],
      habilidades: ['Curativo complexo', 'Segurança do paciente NPSG'],
      anexos: [],
    },
  },
  {
    id: '7',
    nome: 'Dra. Juliana Prado Reis',
    profissao: 'Médico(a)',
    registroProfissional: '88459/PA',
    localNome: 'PRONTO SOCORRO CENTRAL',
    setores: ['GINECOLOGIA'],
    detalhes: {
      fotoUrl: null,
      siglaConselho: 'CRM',
      email: 'jprado@ginecologia.pa.br',
      cpf: '701.928.560-82',
      telefone: '(91) 3202-7733',
      celular: '(91) 99988-7712',
      rg: '5.892.019-SSP/PA',
      orgaoEmissor: 'SSP/PA',
      dataNascimento: '08/12/1983',
      sexo: 'Feminino',
      nomeMae: 'Priscila Prado',
      especialidade: 'Ginecologia e obstetrícia',
      endereco: {
        cep: '66050-230',
        logradouro: 'Alameda Cosme Ferreira',
        numero: '2401',
        complemento: 'Bloco C',
        bairro: 'São Brás',
        cidade: 'Belém',
        uf: 'PA',
      },
      grupos: [
        {
          id: 'g1',
          nome: 'Plantão GO obstétrico',
          local: 'PRONTO SOCORRO CENTRAL',
        },
      ],
      dadosBancarios: {
        banco: '033 — Santander',
        agencia: '4455',
        conta: '770012-3',
        tipoConta: 'Corrente',
        pix: '70192856082',
      },
      resumoFaturamento: 'Notas de serviço emitidas até competência mais recente.',
      contratacao: {
        regime: 'Autônomo recibo',
        dataAdmissao: '15/02/2018',
        cargaHorariaSemanal: '48h em escala quinzenal',
        numeroContrato: 'PSC-2018/00901',
      },
      afastamentos: [
        {
          inicio: '01/04/2024',
          fim: '30/09/2024',
          motivo: 'Licença maternidade',
        },
      ],
      habilidades: ['Parto humanizado', 'Laqueadura videolaparoscópica'],
      anexos: [{ nome: 'CRM_PA_assinado.pdf', tipo: 'PDF', enviadoEm: '15/02/2018' }],
    },
  },
  {
    id: '8',
    nome: 'Dr. Bruno Henrique Alves',
    profissao: 'Médico(a)',
    registroProfissional: '120077/PA',
    localNome: 'HOSPITAL AMAZÔNIA',
    setores: ['CIRURGIA GERAL'],
    detalhes: {
      fotoUrl: null,
      siglaConselho: 'CRM',
      email: 'bruno.alves.cir@live.com',
      cpf: '448.219.330-28',
      telefone: '(91) 3201-9900',
      celular: '(91) 98760-2201',
      rg: '2.300.118-SSP/PA',
      orgaoEmissor: 'SSP/PA',
      dataNascimento: '19/02/1972',
      sexo: 'Masculino',
      nomeMae: 'Maria Alves Couto',
      especialidade: 'Cirurgia geral digestiva',
      endereco: { ...enderecoBelem },
      grupos: [
        { id: 'g1', nome: 'Equipe centro cirúrgico', local: 'HOSPITAL AMAZÔNIA' },
      ],
      dadosBancarios: {
        banco: '756 — Bancoob',
        agencia: '3011',
        conta: '12007-9',
        tipoConta: 'Corrente',
        pix: '',
      },
      resumoFaturamento: 'Honorários CCIH inclusos quando convocado.',
      contratacao: {
        regime: 'Cooperado',
        dataAdmissao: '10/09/2009',
        cargaHorariaSemanal: '60h combinadas centro + ambulatório',
        numeroContrato: 'HC-HA-2009/00044',
      },
      afastamentos: [],
      habilidades: ['Laparoscopia básica', 'Laparotomia urgência'],
      anexos: [],
    },
  },
]
